server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true          # 开启服务发现路由（自动根据服务名创建路由）
          lower-case-service-id: true   # 服务名小写
      routes:
        - id: provider-route
          uri: lb://nacos-discovery-service   # lb:// 表示负载均衡
#          uri: http://localhost:8081
          predicates:
            - Path=/provider/**
          filters:
            - StripPrefix=1
        - id: consumer-route
          uri: lb://consumer-service
          predicates:
            - Path=/consumer/**
          filters:
            - StripPrefix=1
        - id: user-route
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=0      # 保留路径前缀，因为 user-service 的接口路径就是 /user/1
        - id: good-route
          uri: lb://good-service
          predicates:
            - Path=/good/**
          filters:
            - StripPrefix=0
        - id: order-route
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=0
