server:
  port: 8084

spring:
  application:
    name: order-service
#  datasource:
#    url: jdbc:mysql://localhost:3306/order_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 1337281766
#    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.orderservice.entity
  configuration:
    map-underscore-to-camel-case: true
feign:
  sentinel:
    enabled: true
rocketmq:
  name-server: localhost:9876
#  producer:
#    group: user-service-group
#    send-message-timeout: 5000
# Redisson 配置（使用 Redis 单机模式）
redisson:
  single-server-config:
    address: "redis://127.0.0.1:6379"
    password: null          # 如果有密码则填写
    connection-pool-size: 64
    connection-minimum-idle-size: 10